apiVersion: v2
name: kubeatlas
description: Kubernetes Inventory & Governance Platform

type: application

version: 1.0.0
appVersion: "1.0.0"

home: https://github.com/ozcanfpolat/kubeatlas
icon: https://raw.githubusercontent.com/ozcanfpolat/kubeatlas/main/docs/images/logo.png

sources:
  - https://github.com/ozcanfpolat/kubeatlas

maintainers:
  - name: Özcan Polat
    url: https://github.com/ozcanfpolat

keywords:
  - kubernetes
  - inventory
  - cmdb
  - asset-management
  - openshift
  - devops
  - platform-engineering
  - governance

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
